antares_site/antares_site/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'antares_site.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    
    url( r'^admin/', include(admin.site.urls) ),
    url( r'^protracker/', include('protracker.urls', namespace='protracker') ),
)

antares_site/protracker/urls.py
from django.conf.urls import patterns, include, url
from protracker import views

urlpatterns = patterns(
    '',
    url( r'^$', views.index, name='index' ),
    url( r'^alert_search/$', views.alert_search, name='alert_search' ),
    url( r'^(?P<alert_id>\d+)/alert_attr/$', views.alert_attr, name='alert_attr' ),
    url( r'^(?P<alert_id>\d+)/replicas/$', views.replicas, name='replicas' ),
    url( r'^derived_attr/(?P<attrname>\w+-\w+)/$', views.derived_attr, name='derived_attr' ),
    url( r'^derived_attr/rootcode/(?P<sha1>\w+)/$', views.attr_code, name='attr_code' ),
    url( r'^derived_attr/funccode/(?P<funcname>\w+)/(?P<sha1>\w+)/$', views.func_code, name='func_code' ),
    url( r'^(?P<replica_id>\d+)/replica_attr/$', views.replica_attr, name='replica_attr' ),
    url( r'^(?P<replica_id>\d+)/astro/$', views.astro, name='astro' ),
    url( r'^/locus/(?P<locus_id>\d+)/$', views.locus, name='locus' ),
    url( r'^/source/(?P<source_id>\d+)/$', views.source, name='source' ),
    url( r'^/image/(?P<image_id>\d+)/$', views.image, name='image' ),
)

antares_site/protracker/models.py
from django.db import models
from django.core.validators import MinValueValidator

# Create your models here.
class Image( models.Model ):
    """
    The class corresponds to the 'Image' table.
    """
    ImageID = models.IntegerField( primary_key=True )    
    TakenAt = models.DateTimeField( 'Time the image was taken' )
    TelescopeName = models.CharField( max_length=100 )
    FilterPassband = models.CharField( max_length=500 )
    
    def __str__( self ):
        return "Image {0} taken at {1} by telescope {2}".format(
            self.ImageID, self.TakenAt, self.TelescopeName )

class Locus( models.Model ):
    """
    The class corresponds to the 'Locus' table.
    """
    LocusID = models.IntegerField( primary_key=True )
    Coordinate = models.CharField( max_length=500 )
    Uncertainty = models.IntegerField()

    def __str__( self ):
        return "Locus {0} at {1} with uncertainty of {2}".format(
            self.LocusID, self.Coordinate, self.Uncertainty )

class LocusAggregatedAlert( models.Model ):
    """
    The class corresponds to the 'LocusAggregatedAlert' table.
    """
    LAAID = models.IntegerField( primary_key=True )
    LocusID = models.ForeignKey( Locus )
    
class Source( models.Model ):
    """
    The class corresponds to the 'Source' table.
    """
    SourceID = models.IntegerField( primary_key=True )
    ImageID = models.ForeignKey( Image )
    Coordinate = models.CharField( max_length=500 )
    Brightness = models.FloatField()
    DeltaBrightness = models.FloatField()
    ThumbnailURL = models.URLField()

    def __str__( self ):
        return "Source {0} from image {1}".format( self.SourceID, self.ImageID )

class Alert( models.Model ):
    """
    The class corresponds to the 'Alert' table.
    """
    decisions = (
        ( 'NA', 'Not Applicable' ),
        ( 'T', 'Throttled Alert' ),
        ( 'D', 'Diverted immediately' ),
        ( 'L1', 'Level-I Alert' ),
        ( 'L2', 'Level-II Alert' ),
        ( 'R', 'Rarest of the rare Alert' ),
    )

    AlertID = models.IntegerField( primary_key=True )
    TakenAt = models.DateTimeField( 'Time the alert was taken' )
    LocusID = models.ForeignKey( Locus )
    SourceID = models.ForeignKey( Source )
    Decision = models.CharField( max_length=50, choices=decisions, default='NA' )
    # LAAID = models.ForeignKey( LocusAggregatedAlert )

    def __str__( self ):
        return "Alert {0}: {1}".format( self.AlertID, self.Decision )

    def is_throttled( self ):
        return self.Decision == 'T'

    def is_dirverted_immediately( self ):
        return self.Decision == 'D'

    def is_level_1_alert( self ):
        return self.Decision == 'L1'

    def is_level_1_alert( self ):
        return self.Decision == 'L2'

    def is_rarest_of_the_rare( self ):
        return self.Decision == 'R'

class AlertReplica( models.Model ):
    """
    The class corresponds to the 'AlertReplica' table.
    """
    ReplicaID = models.IntegerField( primary_key=True )
    AlertID = models.ForeignKey( Alert )
    # put a >0 constraint on ReplicaNumber field
    ReplicaNumber = models.IntegerField( validators=[MinValueValidator(1)] )
    LocusID = models.ForeignKey( Locus )
    ChannelID = models.IntegerField()
    ChannelProbability = models.FloatField()

    def __str__( self ):
        return "Alert replica {0} of alert {1}".format( self.ReplicaNumber, self.AlertID )

class AstroObject( models.Model ):
    """
    The class corresponds to the 'AlertReplica' table.
    """
    AstroObjectID = models.IntegerField( primary_key=True )
    LocusID = models.ForeignKey( Locus )
    Catalog = models.CharField( max_length=500 )
    IDinCatalog = models.IntegerField()
    IsPointSource = models.BooleanField( default=False )

    def __str__( self ):
        return "Astro object {0} from catalog {1}".format(
            self.AstroObjectID, self.Catalog )

class Attribute( models.Model ):
    """
    The class corresponds to the 'Attribute' table.
    """
    AttrName = models.CharField( max_length=100, primary_key=True )
    IsScaled = models.BooleanField( default=False )
    DataType = models.CharField( max_length=500 )

    def __str__( self ):
        return "Attribute {0}".format(self.AttrName)

class AttributeValue( models.Model ):
    """
    The class corresponds to the 'AttributeValue' table.
    """
    # List of choices of type a container can be
    container_types = (
        ( 'A', 'AstroObject Table' ),
        ( 'C', 'Combo Table' ),
        ( 'I', 'Image Table' ),
        ( 'E', 'Alert Table' ),
        ( 'L', 'LocusAggregatedAlert Table' ),
        ( 'M', 'ImageSection Table' ),
        ( 'R', 'AlertReplica Table' ),
        ( 'S', 'Source Table' ),
    )

    AttributeValueID = models.IntegerField( primary_key=True )
    AttrName = models.ForeignKey( Attribute )
    ContainerID = models.IntegerField()
    ContainerType = models.CharField( max_length=1, choices=container_types )
    ComputedAt = models.DateTimeField( 'Time the value was computed' )
    # For now, just use a string to store value.
    Value = models.CharField( max_length=500 )
    Annotation = models.CharField( max_length=500 )
    Confidence = models.FloatField()

    def __str__( self ):
        return self.Annotation

    class Meta:
        unique_together = ( 'AttrName', 'ContainerID',
                            'ContainerType', 'ComputedAt' )

class DerivedAttribute( models.Model ):
    """
    The class corresponds to the 'DerivedAttribute' table.
    """
    AttrName = models.ForeignKey( Attribute )
    HashName = models.CharField( max_length=40 )
    FunctionName = models.CharField( max_length=50 )
    FileName = models.CharField( max_length=50 )
    PackageName = models.CharField( max_length=50 )
    AstronomerName = models.CharField( max_length=50 )

class ReplicaAssociatedWith( models.Model ):
    """
    The class corresponds to the 'ReplicaAssociatedWith' table.
    """
    ReplicaID = models.ForeignKey( AlertReplica )
    AstroObjectID = models.ForeignKey( AstroObject )
    AssociationProbability = models.FloatField()

antares_site/protracker/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.template import RequestContext, loader
from protracker.models import Alert, Image, Attribute, \
    AttributeValue, DerivedAttribute, AlertReplica, \
    AstroObject, ReplicaAssociatedWith, Locus, Source
from datetime import datetime
from protracker.github import GitHub
import re

decisions = {
    'Throttled Alert': 'T',
    'Diverted immediately': 'D',
    'Level-I Alert': 'L1',
    'Level-II Alert': 'L2',
    'Rarest of the rare Alert': 'R',
}

gituser = 'imsure'
repo = 'antares_provenance_test'

# Create your views here.

def index( request ):
    image_list = Image.objects.all()
    template = loader.get_template( 'protracker/index.html' )
    context = { 'image_list': image_list, 'alert_types': decisions.keys() }
    return render( request, 'protracker/index.html', context )

def alert_search( request ):
    if request.method == "GET":
        taken_at = ( request.GET['taken_at'] )
        d = datetime.strptime(taken_at, '%b. %d, %Y, %H:%M p.m.')
        d = d.date()
        alert_type = ( request.GET['alert_type'] )
        alert_list = Alert.objects.filter( Decision__exact=decisions[alert_type],
                                           TakenAt__year=d.year, TakenAt__month=d.month, TakenAt__day=d.day )
        context = { 'alert_list': alert_list,
                    'taken_at': taken_at,
                    'alert_type': alert_type }
        return render( request, 'protracker/alert_search.html', context )
    
def alert_attr( request, alert_id ):
    alert = get_object_or_404( Alert, pk=alert_id )
    attrs = AttributeValue.objects.filter( ContainerID=alert_id,
                                           ContainerType='E' )
    context = { 'attrs': attrs,
                'alert': alert }
    return render( request, 'protracker/alert_attr.html', context )

def derived_attr( request, attrname ):
    derives = DerivedAttribute.objects.filter( AttrName_id=attrname )
    context = { 'derived_attr': derives[0] }
    return render( request, 'protracker/derived_attr.html', context )

def attr_code( request, sha1 ):
    gh = GitHub()
    commit = gh.repos( gituser, repo ).commits( sha1 ).get()
    url2code = commit['html_url'].replace( 'commit', 'tree' )
    return redirect( url2code )

def func_code( request, funcname, sha1 ):
    gh = GitHub()
    query = """{0} in:file language:py repo:{1}/{2}""".format( funcname, gituser, repo )
    search = gh.search.code.get( q=query )
    url2code = search['items'][0]['html_url']
    sha1_start = url2code.find('/blob/') + 6
    sha1_end = sha1_start + 40
    oldsha1 = url2code[ sha1_start : sha1_end ]
    url2code = url2code.replace( oldsha1, sha1 )
#    url2code += '#L3'
    return redirect( url2code )

def replicas( request, alert_id ):
    reps = AlertReplica.objects.filter( AlertID_id=alert_id )
    context = { 'replicas': reps,
                'alert' : alert_id }
    return render( request, 'protracker/replica.html', context )

def replica_attr( request, replica_id ):
    replica = get_object_or_404( AlertReplica, pk=replica_id )
    attrs = AttributeValue.objects.filter( ContainerID=replica_id,
                                           ContainerType='R' )
    context = { 'attrs': attrs,
                'replica': replica }
    return render( request, 'protracker/replica_attr.html', context )

def astro( request, replica_id ):
    replica_astro = ReplicaAssociatedWith.objects.filter( ReplicaID_id=replica_id )
    astroobj = None
    if replica_astro:
        astroobj = get_object_or_404( AstroObject, AstroObjectID=replica_astro[0].AstroObjectID_id )
    
    context = { 'replica_id' : replica_id,
                'astro' : astroobj }
    return render( request, 'protracker/astro.html', context )

def alert_attr( request, alert_id ):
    alert = get_object_or_404( Alert, pk=alert_id )
    attrs = AttributeValue.objects.filter( ContainerID=alert_id,
                                           ContainerType='E' )
    context = { 'attrs': attrs,
                'alert': alert }
    return render( request, 'protracker/alert_attr.html', context )

def locus( request, locus_id ):
    loc = get_object_or_404( Locus, pk=locus_id )
    context = { 'locus': loc }
    return render( request, 'protracker/locus.html', context )

def source( request, source_id ):
    src = get_object_or_404( Source, pk=source_id )
    context = { 'source': src }
    return render( request, 'protracker/source.html', context )

def image( request, image_id ):
    img = get_object_or_404( Image, pk=image_id )
    context = { 'image': img }
    return render( request, 'protracker/image.html', context )

antares_site/protracker/templates/protracker/alert_attr.html
<!DOCTYPE html>
<html>
<head>
  {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static "style.css" %}" media="screen" />
</head>

  <body>
    <h2>Attributes for Alert {{ alert.AlertID }} </h2>

    {% if attrs %}
    <table stype="width:100%">
      <tr>
	<th>Computed At</th>
	<th>Value</th>
	<th>Confidence</th>
	<th>Name</th>
	<th>Annotation</th>
      </tr>
      {% for attr in attrs %}
      <tr>
	<td>{{ attr.ComputedAt }}</td>
	<td>{{ attr.Value | floatformat:'3' }}</td>
	<td>{{ attr.Confidence | floatformat:'3' }}</td>
	<td>{{ attr.AttrName_id }}</td>
	{% if 'Derived' in attr.Annotation %}
	<td><a href="{% url 'protracker:derived_attr' attr.AttrName_id %}">{{ attr.Annotation }}</a></td>
	{% else %}
	<td>{{ attr.Annotation }}</td>
	{% endif %}
      </tr>
      {% endfor %}
    </table>

    {% else %}
    <h2>No attributes found for alert {{ alert.AlertID }}</h2>
    {% endif %}

  </body>
</html>

antares_site/protracker/templates/protracker/alert_search.html
<!DOCTYPE html>
<html>
<head>
  {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static "style.css" %}" media="screen" />
</head>

  <body>
    <h2>{{ alert_type }} taken at {{ taken_at }}</h2>

    {% if alert_list %}
    <table stype="width:100%">
      <tr>
	<th>Alert ID</th>
	<th>Replicas</th>
	<th>Locus</th>
	<th>Source</th>
	<th>Taken At</th>
	<th>Alert Type</th>
	<th>Attributes</th>
      </tr>
      {% for alert in alert_list %}
      <tr>
	<td>{{ alert.AlertID }}</td>
	<td><a href="{% url 'protracker:replicas' alert.AlertID %}">Replicas</a></td>
	<td><a href="{% url 'protracker:locus' alert.LocusID.LocusID %}">Locus</a></td>
	<td><a href="{% url 'protracker:source' alert.SourceID.SourceID %}">Source</a></td>
	<td>{{ alert.TakenAt }}</td>
	<td>{{ alert_type }}</td>
	<td><a href="{% url 'protracker:alert_attr' alert.AlertID %}">Attributes</a></td>
      </tr>
      {% endfor %}
    </table>

    {% else %}
    <h2>No {{ alert_type }} found at {{ taken_at }}</h2>
    {% endif %}

  </body>
</html>

antares_site/protracker/templates/protracker/astro.html
<!DOCTYPE html>
<html>
<head>
  {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static "style.css" %}" media="screen" />  
</head>

  <body>
    {% if astro %}
    <h2>AstroObject associated with Replica {{ replica_id }}</h2>
    <table stype="width:100%">
      <tr>
	<th>AstroObject ID</th>
	<th>Catalog</th>
	<th>ID in Catalog</th>
	<th>Is Point Source?</th>
	<th>Locus</th>
      </tr>
      <tr>
	<td>{{ astro.AstroObjectID }}</td>
	<td>{{ astro.Catalog }}</td>
	<td>{{ astro.IDinCatalog }}</td>
	<td>{{ astro.IsPointSource }}</td>
	<td><a href="{% url 'protracker:locus' astro.LocusID_id %}">Locus</a></td>
      </tr>
    </table>
    {% else %}
    <h2>No AstroObject associated with Replica {{ replica_id }}</h2>
    {% endif %}

  </body>
</html>

antares_site/protracker/templates/protracker/derived_attr.html
<!DOCTYPE html>
<html>
<head>
  {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static "style.css" %}" media="screen" />  
</head>

  <body>
    <h2>Derived Attribute {{ derived_attr.AttrName_id }}</h2>

    {% if derived_attr %}
    <table stype="width:100%">
      <tr>
	<th>Source Code Version</th>
	<th>Function Name</th>
	<th>File Name</th>
	<th>Package Name</th>
	<th>Astronomer Name</th>
      </tr>
      <tr>
	<td><a href="{% url 'protracker:attr_code' derived_attr.HashName %}">
	    {{ derived_attr.HashName | truncatechars:20 }}</a></td>
	<td><a href="{% url 'protracker:func_code' derived_attr.FunctionName derived_attr.HashName %}">
	    {{ derived_attr.FunctionName }}</a></td>
	<td>{{ derived_attr.FileName }}</td>
	<td>{{ derived_attr.PackageName }}</td>
	<td>{{ derived_attr.AstronomerName }}</td>
      </tr>
    </table>
    {% else %}
    <h2>No derived attributes found!</h2>
    {% endif %}

  </body>
</html>

antares_site/protracker/templates/protracker/image.html
<!DOCTYPE html>

{% if image %}
<p>{{ image.TakenAt }}</p>
<p>{{ image.TelescopeName }}</p>
<p>{{ image.FilterPassband }}</p>
{% else %}
<p>No image found!</p>
{% endif %}

antares_site/protracker/templates/protracker/index.html
<!DOCTYPE html>
<html>
  <head>
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static "style.css" %}" media="screen" />
  </head>

  <body>

    <h1>Welcome to AzNOAOTares Provenance Tracking System</h1>

    <form action="{% url 'protracker:alert_search' %}" method="get">
      <h2>Choose a date</h2>
      {% for image in image_list %}
      <input type="radio" name="taken_at" id="taken_at{{ forloop.counter }}"
	     value="{{ image.TakenAt }}" />
      <label for="taken_at{{ forloop.counter }}">{{ image }}</label><br />
      {% endfor %}

      <h2>Choose an alert type</h2>
      {% for type in alert_types %}
      <input type="radio" name="alert_type" id="alert_type{{ forloop.counter}}"
	     value="{{ type }}" />
      <label for="type{{ forloop.counter}}">{{ type }}</label><br />
      {% endfor %}

      <input type="submit" value="Search" />
    </form>

  </body>
</html>

antares_site/protracker/templates/protracker/locus.html
<!DOCTYPE html>
<html>
<head>
  {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static "style.css" %}" media="screen" />  
</head>

  <body>
    <h2>Locus {{ locus.LocusID }}</h2>
    <table stype="width:100%">
      <tr>
	<th>Locus ID</th>
	<th>Coordinate</th>
	<th>Uncertainty</th>
      </tr>
      <tr>
	<td>{{ locus.LocusID }}</td>
	<td>{{ locus.Coordinate }}</td>
	<td>{{ locus.Uncertainty }}</td>
      </tr>
    </table>
  </body>
</html>

antares_site/protracker/templates/protracker/replica.html
<!DOCTYPE html>
<html>
<head>
  {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static "style.css" %}" media="screen" />
</head>

  <body>
    {% if replicas %}
    <h2>Replicas of alert {{ alert }}</h2>
    <table stype="width:100%">
      <tr>
	<th>Replica ID</th>
	<th>Replica Number</th>
	<th>Locus</th>
	<th>Channel ID</th>
	<th>Channel Probability</th>
	<th>Attributes</th>
	<th>Associated AstroObject</th>
      </tr>
      {% for replica in replicas %}
      <tr>
	<td>{{ replica.ReplicaID }}</td>
	<td>{{ replica.ReplicaNumber }}</td>
	<td><a href="{% url 'protracker:locus' replica.LocusID_id %}">Locus</a></td>
	<td>{{ replica.ChannelID }}</td>
	<td>{{ replica.ChannelProbability | floatformat:'3' }}</td>
	<td><a href="{% url 'protracker:replica_attr' replica.ReplicaID %}">Attributes</a></td>
	<td><a href="{% url 'protracker:astro' replica.ReplicaID  %}">Associated AstroObject</a></td>
      </tr>
      {% endfor %}
    </table>

    {% else %}
    <h2>No replica found for alert {{ alert }}</h2>
    {% endif %}

  </body>
</html>

antares_site/protracker/templates/protracker/replica_attr.html
<!DOCTYPE html>
<html>
<head>
  {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static "style.css" %}" media="screen" />  
</head>

  <body>
    <h2>Attributes for Replica {{ replica.ReplicaID }} of alert {{ replica.AlertID_id }}</h2>

    {% if attrs %}
    <table stype="width:100%">
      <tr>
	<th>Computed At</th>
	<th>Value</th>
	<th>Confidence</th>
	<th>Name</th>
	<th>Annotation</th>
      </tr>
      {% for attr in attrs %}
      <tr>
	<td>{{ attr.ComputedAt }}</td>
	<td>{{ attr.Value }}</td>
	<td>{{ attr.Confidence | floatformat:'3' }}</td>
	<td>{{ attr.AttrName_id }}</td>
	{% if 'Derived' in attr.Annotation %}
	<td><a href="{% url 'protracker:derived_attr' attr.AttrName_id %}">{{ attr.Annotation }}</a></td>
	{% else %}
	<td>{{ attr.Annotation }}</td>
	{% endif %}
      </tr>
      {% endfor %}
    </table>

    {% else %}
    <h2>No attributes found for alert {{ alert.AlertID }}</h2>
    {% endif %}

  </body>
</html>

antares_site/protracker/templates/protracker/source.html
<!DOCTYPE html>
<html>
<head>
  {% load staticfiles %}
  <link rel="stylesheet" type="text/css" href="{% static "style.css" %}" media="screen" />  
</head>

  <body>
    <h2>Source {{ source.SourceID }}</h2>
    <table stype="width:100%">
      <tr>
	<th>Source ID</th>
	<th>Coordinate</th>
	<th>Brightness</th>
	<th>DeltaBrightness</th>
	<th>ThumbnailURL</th>
	<th>Image</th>
      </tr>
      <tr>
	<td>{{ source.SourceID }}</td>
	<td>{{ source.Coordinate }}</td>
	<td>{{ source.Brightness | floatformat:'3' }}</td>
	<td>{{ source.DeltaBrightness | floatformat:'3' }}</td>
	<td>{{ source.ThumbnailURL }}</td>
	<td><a href="{% url 'protracker:image' source.ImageID_id %}">Image</a></td>
      </tr>
    </table>
  </body>
</html>